### PR TITLE
Add support for SUSE release version

### PR DESCRIPTION
**Pull request by mindmelting**
Question whether the patch version should be part of the release parameter or not...

### CODE REVIEW

**Comment by wblankenship** [comment]
Hey @mindmelting,

Do you mind showing me the difference in output for this PR? I.E. what getOS it currently is showing on SUSE vs what was expected and implemented in this PR?

**Comment by wblankenship** [comment]
(I don't have a SUSE box readily available)

**Comment by mindmelting** [comment]
@wblankenship it currently does not return release information, this PR will add the release information (see the test that has been composed to view expected input/output)

**Comment by winfinit** [comment]
there would be an issue with this, i've setup myself with "SUSE Linux Enterprise Server 11 (x86_64)" and it has multiple release files also
```
linux-68fg:~/workspace/test/getos-master # ls -lah /etc/*-release
-rw-r--r-- 1 root root 110 May  5  2010 /etc/lsb-release
-rw-r--r-- 1 root root 156 Jun 19 17:07 /etc/os-release
-rw-r--r-- 1 root root  69 Jun 19 17:07 /etc/SuSE-release
```
so because SuSE below ubuntu, so it identifies it as ubuntu due to lsb-release:
```
linux-68fg:~/workspace/test/getos-master # node test.js 
{"os":"linux","dist":"SUSE Linux"}
```

with moving getOS above ubuntu "/etc/lsb-release", then with applied patch i am getting:
```
linux-68fg:~/workspace/test/getos-master # node test.js 
{"os":"linux","dist":"SUSE Linux","release":"11"}
```

**Comment by mindmelting** [comment]
Interesting the SUSE Enterprise Server 11 box I am running this on only has the following:

```
+ ls -lah /etc/os-release /etc/SuSE-release
-rw-r--r-- 1 root root 156 Jun 19 17:07 /etc/os-release
-rw-r--r-- 1 root root  69 Jun 19 17:07 /etc/SuSE-release
```

**Comment by winfinit** [comment]
I have patch 4, downloaded today, without any extra packages installed

**Comment by mindmelting** [comment]
I also have patch 4....!
```
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4
```

**Comment by winfinit** [comment]
@mindmelting are you going to update os.json for this pull request?

**Comment by winfinit** [comment]
@mindmelting apologies, didn't check before I wrote this, you already did, thank you! @wblankenship do you have any concerns at the moment with this PR?

**Comment by wblankenship** [comment]
Nope, this loos good to me :+1:

**Comment by wblankenship** [comment]
@mindmelting pushed to npm in https://github.com/wblankenship/getos/commit/2c47ad31a3815a114c72c501dff5219ac1f42ab6

**Comment by mindmelting** [comment]
Great!

**Pull request merged**
